### PR TITLE
Fix inappropriate images

### PR DESCRIPTION
**Pull request by mitsuruog**
Update inappropriate images.

Here.
React Styleguidist  isolated React component development environment with a living style guide

and here.
React Styleguidist  isolated React component development environment with a living style guide (1)

Related

- Please update example GIF with appropriate content · https://github.com/styleguidist/react-styleguidist/issues/1534

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks! `workbench.png` is now three times bigger, could you please optimize it?

**Comment by mitsuruog** [comment]
good point! Let me try it.

**Comment by mitsuruog** [comment]
@sapegin review me again.

**Comment by sapegin** [comment]
Cool, thanks!

**Pull request merged**
